// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuUSstXKWSUrQiAEzNMr7_PsPQoGNlWcs',
    appId: '1:362435952829:web:f843b580e213d9872df7d4',
    messagingSenderId: '362435952829',
    projectId: 'ecocollect-bc0e4',
    authDomain: 'ecocollect-bc0e4.firebaseapp.com',
    storageBucket: 'ecocollect-bc0e4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb18r4elljPBWtYPre9IPOxNAesDmNmdw',
    appId: '1:362435952829:android:73a3dd1eddf035172df7d4',
    messagingSenderId: '362435952829',
    projectId: 'ecocollect-bc0e4',
    storageBucket: 'ecocollect-bc0e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVkKd3kSzuqkIYLpwt1BiSCzzl_UPq6h4',
    appId: '1:362435952829:ios:8c91f904adf6ecad2df7d4',
    messagingSenderId: '362435952829',
    projectId: 'ecocollect-bc0e4',
    storageBucket: 'ecocollect-bc0e4.firebasestorage.app',
    iosBundleId: 'com.example.ecocollect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVkKd3kSzuqkIYLpwt1BiSCzzl_UPq6h4',
    appId: '1:362435952829:ios:8c91f904adf6ecad2df7d4',
    messagingSenderId: '362435952829',
    projectId: 'ecocollect-bc0e4',
    storageBucket: 'ecocollect-bc0e4.firebasestorage.app',
    iosBundleId: 'com.example.ecocollect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuUSstXKWSUrQiAEzNMr7_PsPQoGNlWcs',
    appId: '1:362435952829:web:029d4d02ad4180eb2df7d4',
    messagingSenderId: '362435952829',
    projectId: 'ecocollect-bc0e4',
    authDomain: 'ecocollect-bc0e4.firebaseapp.com',
    storageBucket: 'ecocollect-bc0e4.firebasestorage.app',
  );
}
